apiVersion: monitoring.coreos.com/v1
kind: ThanosRuler
metadata:
  labels:
    app.kubernetes.io/component: thanos-ruler
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: thanos-ruler
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.31.0
  name: k8s
  namespace: kubesphere-monitoring-system
spec:
  alertmanagersUrl: []
  evaluationInterval: 1m
  image: thanosio/thanos:v0.31.0
  podMetadata:
    labels:
      app.kubernetes.io/component: thanos-ruler
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: thanos-ruler
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.31.0
  queryEndpoints: []
  replicas: 2
  resources:
    requests:
      memory: 200Mi
  ruleNamespaceSelector: null
  ruleSelector: {}
